// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/dbService.proto

package dbService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for DbService service

func NewDbServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for DbService service

type DbService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (DbService_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (DbService_PingPongService, error)
}

type dbService struct {
	c    client.Client
	name string
}

func NewDbService(name string, c client.Client) DbService {
	return &dbService{
		c:    c,
		name: name,
	}
}

func (c *dbService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "DbService.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (DbService_StreamService, error) {
	req := c.c.NewRequest(c.name, "DbService.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &dbServiceStream{stream}, nil
}

type DbService_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type dbServiceStream struct {
	stream client.Stream
}

func (x *dbServiceStream) Close() error {
	return x.stream.Close()
}

func (x *dbServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *dbServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *dbServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *dbServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dbService) PingPong(ctx context.Context, opts ...client.CallOption) (DbService_PingPongService, error) {
	req := c.c.NewRequest(c.name, "DbService.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &dbServicePingPong{stream}, nil
}

type DbService_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type dbServicePingPong struct {
	stream client.Stream
}

func (x *dbServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *dbServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *dbServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *dbServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *dbServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *dbServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for DbService service

type DbServiceHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, DbService_StreamStream) error
	PingPong(context.Context, DbService_PingPongStream) error
}

func RegisterDbServiceHandler(s server.Server, hdlr DbServiceHandler, opts ...server.HandlerOption) error {
	type dbService interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type DbService struct {
		dbService
	}
	h := &dbServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&DbService{h}, opts...))
}

type dbServiceHandler struct {
	DbServiceHandler
}

func (h *dbServiceHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.DbServiceHandler.Call(ctx, in, out)
}

func (h *dbServiceHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.DbServiceHandler.Stream(ctx, m, &dbServiceStreamStream{stream})
}

type DbService_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type dbServiceStreamStream struct {
	stream server.Stream
}

func (x *dbServiceStreamStream) Close() error {
	return x.stream.Close()
}

func (x *dbServiceStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *dbServiceStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *dbServiceStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *dbServiceStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *dbServiceHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.DbServiceHandler.PingPong(ctx, &dbServicePingPongStream{stream})
}

type DbService_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type dbServicePingPongStream struct {
	stream server.Stream
}

func (x *dbServicePingPongStream) Close() error {
	return x.stream.Close()
}

func (x *dbServicePingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *dbServicePingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *dbServicePingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *dbServicePingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *dbServicePingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
